language: go

# use containers which run faster and have cache
sudo: false

addons:
  apt:
    packages:
      - jq

cache:
  directories:
    $GOPATH/src

go:
  - tip
  - 1.7.x

go_import_path: github.com/adamryman/kit

before_install:
  - jq --version
  - go get github.com/alecthomas/gometalinter
  - gometalinter -i -d

script:
  - go build -v github.com/adamryman/kit/...
  - gometalinter --enable-all --json $GOPATH/src/github.com/adamryman/kit/... | jq -C .

notifications:
  email: false
